package main

import (
	"context"
	"errors"
	"fmt"
	"os"

	"github.com/spf13/cobra"

	"github.com/barad1tos/noxctl/bear/cli/destroy"
)

// destroyAutoApprove is the --auto-approve flag binding. When true,
// the type-to-confirm prompt is skipped; required for non-interactive
// (CI / script) invocations.
var destroyAutoApprove bool

// destroyCmd removes every Bear note carrying the supplied managed
// tag. Master + hub notes (auto-generated by the regen pipeline) are
// soft-deleted via `bearcli trash` and remain restorable; atomic
// notes (operator-authored content) have only their canonical
// tag-line stripped — the body content survives.
//
// Type-to-confirm guards against fat-fingered invocations: the
// operator must type the tag name verbatim before any mutation
// runs. `--auto-approve` bypasses the prompt for CI / scripts.
//
// Exit codes:
//
//   - 0 — destroy completed; counts printed on stdout
//   - 1 — tag not in catalog, partial-sweep failure, or operator
//     aborted the type-to-confirm prompt
var destroyCmd = &cobra.Command{
	Use:   "destroy <tag>",
	Short: "Remove a managed Bear tag (trash master+hub, strip canonical from atoms)",
	Long: `destroy removes the master and hub notes auto-generated
for a managed tag, and strips the canonical tag-line from every
atomic note carrying that tag. Atom bodies are preserved — only the
link into the managed structure is removed.

Master + hub notes go to Bear's trash and can be restored via
'bearcli restore' or the Bear UI; the strip on atomic notes is a
plain content edit, also recoverable through Bear's per-note
history.

The first positional argument is the tag to destroy (e.g.
'library/poetry'). The tag must exist in the loaded catalog —
destroy refuses to operate on tags it doesn't know about so a typo
can't accidentally walk an unmanaged corner of the vault.

By default destroy prompts for type-to-confirm: type the tag name
verbatim to proceed; anything else aborts. Pass --auto-approve for
non-interactive (CI / script) runs.`,
	Args: cobra.ExactArgs(1),
	RunE: runDestroy,
}

// runDestroy is the destroy RunE. Loads the catalog, hands the
// orchestration off to bear/cli/destroy.Run, and maps the typed
// sentinels back to readable stderr lines before propagating.
func runDestroy(cmd *cobra.Command, args []string) error {
	domains, loadErr := domainsWithPreflight()
	if loadErr != nil {
		return loadErr
	}
	return runWithSignalContext(cmd, func(ctx context.Context) error {
		err := destroy.Run(ctx, destroy.Options{
			Domains:     domains,
			Tag:         args[0],
			AutoApprove: destroyAutoApprove,
			Stdout:      os.Stdout,
			Stderr:      os.Stderr,
			Stdin:       os.Stdin,
		})
		if errors.Is(err, destroy.ErrAborted) {
			_, _ = fmt.Fprintln(os.Stderr, "noxctl destroy: aborted")
		}
		return err
	})
}

func init() {
	destroyCmd.Flags().BoolVar(&destroyAutoApprove, "auto-approve", false,
		"skip the type-to-confirm prompt (required for non-interactive runs)")
	rootCmd.AddCommand(destroyCmd)
}
