package main

import (
	"context"
	"errors"
	"fmt"
	"os"

	"github.com/spf13/cobra"

	"github.com/barad1tos/noxctl/bear/bearcli"
	"github.com/barad1tos/noxctl/bear/cli"
	"github.com/barad1tos/noxctl/bear/engine"
)

// destroyAutoApprove is the --auto-approve flag binding. When true,
// the type-to-confirm prompt is skipped; required for non-interactive
// (CI / script) invocations.
var destroyAutoApprove bool

// errDestroyAborted is the cmd-layer sentinel for the abort path.
// main.go silences it before exit so the operator does not see both
// "noxctl destroy: aborted" (from runDestroy below) AND Cobra's own
// `Error: destroy: aborted by operator` (from SilenceErrors: false).
var errDestroyAborted = errors.New("noxctl destroy: aborted")

// destroyCmd removes every Bear note carrying the supplied managed
// tag. Master + hub notes (auto-generated by the regen pipeline) are
// soft-deleted via `bearcli trash` and remain restorable; atomic
// notes (operator-authored content) have only their canonical
// tag-line stripped — the body content survives.
//
// Type-to-confirm guards against fat-fingered invocations: the
// operator must type the tag name verbatim before any mutation
// runs. `--auto-approve` bypasses the prompt for CI / scripts.
//
// Exit codes:
//
//   - 0 — destroy completed; counts printed on stdout
//   - 1 — tag not in catalog, partial-sweep failure, or operator
//     aborted the type-to-confirm prompt
var destroyCmd = &cobra.Command{
	Use:   "destroy <tag>",
	Short: "Remove a managed Bear tag (trash master+hub, strip canonical from atoms)",
	Long: `destroy removes the master and hub notes auto-generated
for a managed tag, and strips the canonical tag-line from every
atomic note carrying that tag. Atom bodies are preserved — only the
link into the managed structure is removed.

Master + hub notes go to Bear's trash and can be restored via
'bearcli restore' or the Bear UI; the strip on atomic notes is a
plain content edit, also recoverable through Bear's per-note
history.

The first positional argument is the tag to destroy (e.g.
'library/poetry'). The tag must exist in the loaded catalog —
destroy refuses to operate on tags it doesn't know about so a typo
can't accidentally walk an unmanaged corner of the vault.

By default destroy prompts for type-to-confirm: type the tag name
verbatim to proceed; anything else aborts. Pass --auto-approve for
non-interactive (CI / script) runs.`,
	Args: cobra.ExactArgs(1),
	RunE: runDestroy,
}

// runDestroy is the destroy RunE. Loads the catalog, hands the
// orchestration off to bear/cli/cli.RunDestroy, and maps the typed
// sentinels back to readable stderr lines before propagating.
func runDestroy(cmd *cobra.Command, args []string) error {
	domains, _, _, loadErr := domainsWithPreflight()
	if loadErr != nil {
		return loadErr
	}
	// Initialize the bearcli pool — destroy issues bearcli list +
	// trash + overwrite calls and would otherwise fail with "pool not
	// initialized". Mirrors the init in apply.go / daemon.go / verify.go.
	bearcli.SetConcurrency(engine.DefaultBearcliConcurrency)
	return runWithSignalContext(cmd, func(ctx context.Context) error {
		err := cli.RunDestroy(ctx, cli.DestroyOptions{
			Domains:     domains,
			Tag:         args[0],
			AutoApprove: destroyAutoApprove,
			Stdout:      os.Stdout,
			Stderr:      os.Stderr,
			Stdin:       os.Stdin,
		})
		if errors.Is(err, cli.ErrAborted) {
			_, _ = fmt.Fprintln(os.Stderr, "noxctl destroy: aborted")
			// Silence Cobra's redundant `Error: ...` line for the
			// abort path only — every other error path still prints
			// through Cobra normally. The cmd-layer sentinel main.go
			// matches against drives the exit code.
			cmd.SilenceErrors = true
			return errDestroyAborted
		}
		// cli.RunDestroy wraps ctx.Err() (context.Canceled) when apply
		// bails mid-sweep on SIGINT. Translate to the shared
		// errInterrupted sentinel so main.go maps to POSIX exit 130
		// (same as apply); without this, canceled destroy exits 1
		// indistinguishable from a generic error.
		if errors.Is(err, context.Canceled) || errors.Is(err, context.DeadlineExceeded) {
			return errInterrupted
		}
		return err
	})
}

func init() {
	destroyCmd.Flags().BoolVar(&destroyAutoApprove, "auto-approve", false,
		"skip the type-to-confirm prompt (required for non-interactive runs)")
	rootCmd.AddCommand(destroyCmd)
}
