package main

import (
	"errors"
	"fmt"
	"io/fs"
	"os"

	"github.com/spf13/cobra"
)

// initSubCmd writes a starter noxctl.toml template at the requested
// path. The template is annotated with comments explaining each
// field; the operator edits it and runs `noxctl validate` to confirm
// the schema before `noxctl apply`.
//
// Non-interactive on purpose. CLAUDE.md commits the project to a
// single non-stdlib runtime dependency; an interactive wizard would
// pull in a TUI ecosystem (huh + bubbletea + lipgloss + transitive
// deps) for a one-shot bootstrap step. The template+edit flow is
// simpler, deterministic, and works in CI / scripts.
var initSubCmd = &cobra.Command{
	Use:   "init [path]",
	Short: "Write a starter noxctl.toml template to disk",
	Long: `init writes an annotated noxctl.toml template at the
supplied path (default ./noxctl.toml). The template ships three
blueprint examples — flat-list, flat-table, hub-routed — with
inline comments explaining each field. Edit it to match your Bear
vault, then run 'noxctl validate <path>' to confirm the schema
parses before 'noxctl apply'.

Fails loudly when the target path already exists — init never
overwrites existing config. Pass --force to replace.`,
	Args: cobra.MaximumNArgs(1),
	RunE: runInit,
}

var initForce bool // --force overwrite existing file

// runInit is the init RunE. Resolves the target path from the
// positional arg (falls back to ./noxctl.toml), refuses to clobber
// an existing file unless --force, writes the embedded starter
// template, and prints a one-line success summary on stderr.
func runInit(_ *cobra.Command, args []string) error {
	path := defaultConfigPath
	if len(args) == 1 {
		path = args[0]
	}

	if !initForce {
		if _, err := os.Stat(path); err == nil {
			return fmt.Errorf("noxctl init: %s already exists; pass --force to overwrite", path)
		} else if !errors.Is(err, fs.ErrNotExist) {
			return fmt.Errorf("noxctl init: stat %s: %w", path, err)
		}
	}

	if err := os.WriteFile(path, []byte(starterTemplate), 0o644); err != nil {
		return fmt.Errorf("noxctl init: write %s: %w", path, err)
	}

	if !quiet {
		_, _ = fmt.Fprintf(os.Stderr,
			"✓ wrote %s. Edit it to match your vault, then run `noxctl validate %s`.\n",
			path, path,
		)
	}
	return nil
}

func init() {
	initSubCmd.Flags().BoolVar(&initForce, "force", false,
		"overwrite the target path if it already exists")
	rootCmd.AddCommand(initSubCmd)
}

// starterTemplate is the annotated noxctl.toml body init writes.
// Mirrors examples/minimal.toml in shape so an operator who reads
// either source sees the same three-blueprint starter.
const starterTemplate = `# noxctl.toml — starter catalog generated by 'noxctl init'
#
# Edit the [[domain]] blocks below to match the Bear tags you
# actually use. Run 'noxctl validate <path>' to check the file
# without touching Bear, then 'noxctl plan' to preview the diff
# against your live vault.
#
# Three blueprints are shown — flat-list, flat-table, hub-routed.
# The full catalog of six (flat-list, flat-table, grouped-vertical,
# hub-routed, hub-routed-with-subtag, umbrella) is documented in
# examples/personal.toml in the repository.

[meta]
  version = "1"
  # locale picks the master/hub copy language. "uk" is the only
  # locale shipped today; pass "" or omit to fall back.
  locale = "uk"

# flat-list: one master note, every atom under the tag becomes a
# wikilink bullet on it. Simplest blueprint; good for capture-style
# tags where order doesn't matter.
[[domain]]
  tag         = "inbox"
  index_title = "✱ Inbox"
  blueprint   = "flat-list"

# flat-table: master is a bucketed table. Pre-declare the buckets
# and the "unknown bucket" name; atoms whose canonical line names
# an undeclared bucket land under unknown_bucket.
[[domain]]
  tag            = "library/quotes"
  index_title    = "✱ Quotes"
  blueprint      = "flat-table"
  buckets        = ["Books", "Films", "Talks"]
  unknown_bucket = "Other"

# hub-routed: each bucket gets its own Tier-2 hub note, and the
# master lists every hub. hub_h2_prefix is the heading the renderer
# emits inside each hub (e.g. "Poems by Author").
[[domain]]
  tag            = "library/poetry"
  index_title    = "✱ Poetry"
  blueprint      = "hub-routed"
  unknown_bucket = "Unknown"
  hub_h2_prefix  = "Poems"
`
